export const GET_HOURLY_EVENTS = 'GET_HOURLY_EVENTS';
export const GET_DAILY_EVENTS = 'GET_DAILY_EVENTS';
export const GET_HOURLY_STATS = 'GET_HOURLY_STATS';
export const GET_DAILY_STATS = 'GET_DAILY_STATS';
export const GET_POI = 'GET_POI';
